### PR TITLE
fix urn display css

### PR DESCRIPTION
**Pull request by miltontony**

### CODE REVIEW

**Comment by KaitCrawford** [comment]
Urns displayed on the inbox page are displaying poorly due to a lack of space.
This adjusts the css to improve the display.
Before changes:
urns display

After changes:
new_display

**Comment by miltontony** [comment]
@rowanseymour small review please

**Comment by rowanseymour** [comment]
@miltontony I think it looks better when labels are aligned. 

For now, you guys are always going to display a full telephone number, and we'll always display the six character anon id. So I think we can have switch the width of that column depending on SITE_CONTACT_DISPLAY. That way it will be unchanged for us, but you guys will get more space for phone numbers

**Comment by miltontony** [comment]
Closing this and replacing it with #209

**Pull request closed without merging**
