### PR TITLE
Require token auth on Junebug optouts

### PR DESCRIPTION
**Pull request by KaitCrawford**
An addition to the Identity Store/Junebug integration:
This ensures that requests to the view for receiving opt out notifications from the Identity Store require Token Authentication to be successful.

### CODE REVIEW

**Comment by KaitCrawford** [comment]
@hodgestar Here's the PR for review.

**Comment by KaitCrawford** [comment]
@rowanseymour Please review this small PR for an addition Junebug backend.

**Comment by rowanseymour** [comment]
Am fine to merge this whenever you guys have reviewed internally

**Comment by hodgestar** [comment]
@rowanseymour We are happy internally, merge when ready! :D

**Comment by hodgestar** [comment]
@rowanseymour Thanks!

**Pull request merged**
